# -*- coding: utf-8 -*-
"""Adivinhe_Num.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxe27dIT4vLn5-AbCNT6lAzyPS0h9wQI

# 🎮 Jogo: Adivinhe o Número

## 🧠 O que este programa faz?
O computador escolhe um número aleatório entre **1 e 20**.  
Você deve tentar adivinhar esse número em até **5 tentativas**.

A cada tentativa, o programa informa se o valor digitado é:
- 📉 Muito alto  
- 📈 Muito baixo  
- 🎉 Correto  

---

## 📚 O que você aprende com este código?

### 🔁 Repetição (`while`)
O jogo continua enquanto ainda houver tentativas.

### 🔀 Decisão (`if / else`)
O programa compara seu palpite com o número secreto:
- Igual → você acerta  
- Maior → "muito alto"  
- Menor → "muito baixo"  

### 📦 Listas (`[]`)
Os palpites são guardados em uma lista:
`palpites.append(palpite)`

### 🔢 Contagem (`len()`)
Usado para verificar quantas partidas já foram jogadas (placar).

---

## 🎯 Objetivo
Praticar lógica de programação usando:
- Entrada de dados (`input`)
- Estruturas de decisão
- Estruturas de repetição
- Listas

---

💡 **Desafio:**
- Mude o intervalo (ex: 1 a 50)  
- Aumente o número de tentativas  
- Crie níveis de dificuldade
"""

import random

# Placar (lista)
pontuacoes = []

def jogar():
    numero = random.randint(1, 40)
    palpites = []

    tentativas = 0
    max_tentativas = 5

    print("\n🎮 Adivinhe o número de 1 a 40!")

    while tentativas < max_tentativas:
        palpite = int(input("Digite seu palpite: "))

        palpites.append(palpite)
        tentativas += 1

        if palpite == numero:
            print("🎉 Acertou!")

            pontos = (max_tentativas - tentativas + 1) * 10
            print("Pontuação:", pontos)

            pontuacoes.append(pontos)
            print("Seus palpites:", palpites)
            return

        else:
            if palpite > numero:
                print("Muito alto!")
            else:
                print("Muito baixo!")

    print("\n😢 Você perdeu!")
    print("Número era:", numero)
    print("Palpites:", palpites)

    pontuacoes.append(0)

def mostrar_placar():
    if len(pontuacoes) == 0:
        print("Nenhuma partida jogada.")
    else:
        print("\n📊 Placar:")
        for i, p in enumerate(pontuacoes):
            print(f"Rodada {i+1}: {p} pontos")

def menu():
    while True:
        print("\n1 - Jogar")
        print("2 - Placar")
        print("3 - Sair")

        opcao = input("Escolha: ")

        if opcao == "1":
            jogar()
        elif opcao == "2":
            mostrar_placar()
        elif opcao == "3":
            break
        else:
            print("Opção inválida!")

menu()